export const getData = async( ) =>{
    try {

    } catch (error) {
        console.error(error)
        throw new Error("Error")
    }
}